# @format
name: Deploy Prefect flow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            **/requirements.txt

      # Clear any existing Prefect installations
      - name: Clear existing Prefect
        run: |
          pip uninstall -y prefect prefect-github
          pip cache purge

      # Install dependencies with explicit versions
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "prefect>=3.0.0"
          pip install "prefect-github>=0.3.0"
          prefect block register -m prefect_github

      - name: Check Prefect Version
        run: |
          python -c "import prefect; print(f'Prefect version: {prefect.__version__}')"
          python -c "import prefect_github; print(f'Prefect-GitHub version: {prefect_github.__version__}')"

      - name: Prefect Auth
        uses: PrefectHQ/actions-prefect-auth@v1
        with:
          prefect-api-key: ${{ secrets.PREFECT_API_KEY }}
          prefect-workspace: "wasteology/default"

      - name: Create GitHub Credentials Block
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python - <<'EOF' | python -c "import sys; exec(sys.stdin.read())"
          from prefect.blocks.system import Secret
          from prefect_github import GitHubCredentials

          # Create Secret block for GitHub token
          secret_block = Secret(value="${{ secrets.GITHUB_TOKEN }}")
          secret_block.save("github-token-secret", overwrite=True)

          # Create GitHub Credentials using the secret
          github_creds = GitHubCredentials(
              token=Secret.load("github-token-secret")
          )
          github_creds.save('github-credentials', overwrite=True)
          EOF

      - name: Create GitHub Repository Block
        run: |
          python - <<'EOF' | python -c "import sys; exec(sys.stdin.read())"
          from prefect_github import GitHubRepository
          github_repo = GitHubRepository(
              repository='${{ github.repository }}',
              reference='${{ github.ref_name }}',
              credentials='github-credentials'
          )
          github_repo.save('cietrade-etl-repo', overwrite=True)
          EOF

      - name: Deploy Flow
        run: python workflows/deploy.py
