# @format

name: Deploy Prefect flow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install prefect-github
          prefect block register -m prefect_github

      - name: Prefect Auth
        uses: PrefectHQ/actions-prefect-auth@v1
        with:
          prefect-api-key: ${{ secrets.PREFECT_API_KEY }}
          prefect-workspace: "wasteology/default"

      - name: Create GitHub Credentials Block
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python - <<EOF
          from prefect_github import GitHubCredentials
          from prefect.blocks.system import Secret

          # First create a Secret block for the GitHub token
          secret_block = Secret(value="${{ secrets.GITHUB_TOKEN }}")
          secret_block.save("github-token-secret", overwrite=True)

          # Then create the GitHub Credentials block using the secret
          github_creds = GitHubCredentials(
              token=Secret.load("github-token-secret")
          )
          github_creds.save('github-credentials', overwrite=True)
          EOF

      - name: Create GitHub Repository Block
        run: |
          python - <<EOF
          from prefect_github import GitHubRepository
          github_repo = GitHubRepository(
              repository='${{ github.repository }}',
              reference='${{ github.ref_name }}',
              credentials='github-credentials'
          )
          github_repo.save('cietrade-etl-repo', overwrite=True)
          EOF

      - name: Deploy Flow
        run: python workflows/deploy.py
